package.json
---
our database.js file under /db requires package.json and attempts to access a database called whatever the .name quality on package.json is. from the boilermaker workshop, this name was "boilermaker." I changed it to "grace-shopper" so that we can work with a graceshopper database.
=> changed pkg name to grace-shopper. 

package.json, server/api/index.js, server/api/products.js
---
created a new backend file "products.js" under /server/api to handle all products routes. In it i've set up a single get request for all products.
=> All product route

client/store/index.js, client/store/products.js, server/api/index.js
---
fixed a missing period in /api/index.js when calling products file, and also created a file within /client/store called products.js which hosts a products store and its thunk and reducer for getting all products.
=> Redux all products

client/components/navbar.js, client/store/index.js, client/store/products.js, server/api/index.js
=> Redux store single product

client/store/products.js
=> .data added to axios req

.travis.yml
=> token for travis

server/db/models/user.js
---
added isAdmin field to user model in /db/models/user
=> added isAdmin field to user model in /db/models/user

client/components/navbar.js, client/routes.js
Added link to home in navbar
Disabled default login component from showing up on homepage for now
=> added link to home in nav-bar

client/components/all-products.js, client/components/navbar.js, public/style.css
=> potential css layout

script/seed.js, server/db/models/order.js
=> refactor: add cart status to order model

server/db/models/product.spec.js, server/db/models/user.spec.js
wrote a test spec to check of product was created in db
=> test: create Product testspec

client/store/products.spec.js
Test Specs Written
- product thunk spec
=> Test: product thunk spec

client/components/single-product.js, public/index.html, public/style.css
made single product page nicer
=> style: single product page

package-lock.json, package.json
ran "npm install --save-dev redux-immutable-state-invariant" to add dependency for thunk test specs to work on travis
=> refactor: added dependency for testing

client/store/products.spec.js, server/db/models/product.js, server/db/models/product.spec.js
- removed describe.only (left in by accident last push)
- added edit product methods
- fixed delete product
=> feat: product-instance methods, test specs

script/seed.spec.js, server/api/products.spec.js, server/db/models/order.spec.js
test : 
1)test specs added in api/products.spec (the last spec is still not passing! will work on it on weekend.
2)test specs added on seed.spec file
3) test specs added on order.spec file( working on passing the test)
=> test: new test specs added in seed file and api/products

client/components/cart.js, client/components/navbar.js, client/components/single-product.js, client/routes.js, client/store/user.js, server/api/cart.js, server/db/models/order.js
---
- Added an "add to cart button" on the single product page. This calls the thunk fetchAddToCart which, for now, correctly updates an order in the database for a logged in user, but i am lacking the part where i update the lineItems table with this info. working on that assocaition now.
=> Cart branch

script/seed-users.js, script/seed.js
Seeded 100 users
First two are admin for testing purposes
=> chore: fake user seed created

script/seed-lineitems.js, script/seed-orders.js, script/seed-products.js, script/seed.js
Sorry! I should've done this all at once.
Moved products, orders, and lineitems to their own respective file.
Imported the respective files into seed.js
=> refactor: moved seedings to their own files

client/components/guestCart.js, client/routes.js, client/store/guestCartFuncs.js
guest cart can be viewed, and quantity in cart can be changed
(there is some dummy data and a fake route at the moment for testing purposes if you want to see it in action)
=> Guest cart

script/seed-users.js
gave our users some names so they aren't just emails
=> refactor: added names to users

client/components/product-preview.js, client/components/single-product.js, public/style.css
=> style single product view

client/store/user.js, server/api/cart.js
=> minor change

client/components/auth-form.js, client/components/navbar.js, public/style.css
style: login and signup pages are restyled
=> style: login and signup pages restyled

public/style.css, script/seed-products.js
* added 7 ducks to seed file
* fix: might've deleted a closing bracket when merging to master in previous pull request. added it back in style.css file
=> chore: seed products with more ducks

client/components/guestCart.js, client/store/guestCartFuncs.js
guest cart page reloads on click of delete button to reflect state change
=> feat: delete item from guest cart

client/components/navbar.js
=> feat:cart button

client/components/navbar.js, client/routes.js
=> feat: add link to cart for guest users

server/db/models/lineItem.js, server/db/models/order.js, server/db/models/product.js, server/db/models/user.js
* Order/Product/Lineitem - quantity and prices have minimum value 0 (can't have negative)
* User email must be email and can't be null
* User password can't be null
=> refactor: additional model validations

client/components/user-home.js
Changed "Welcome, {name}" back to "Welcome, {email}".
=> refactor: changed welcome message to email instead of name

client/components/cart.js, client/components/checkout.js, client/components/guestCart.js, client/store/user.js
=> Checkout branch

client/components/admin-addProduct.js, client/components/admin-editProduct.js, client/components/admin-productForm.js, client/components/admin-viewProducts.js, client/components/user-home.js, client/store/admin-products.js, server/api/authentication.js, server/api/products.js, server/db/models/product.js
Product Model
- deleted instance methods
API
- added put/post/delete api routes for products
- added authentication middleware to prevent these routes from being accessed by anyone
REACT /client/component
- add product comp
- edit product comp 
- product form 
REDUX /store/admin-products
- action creators and thunks for put/post/delete 
- removed a console.log from user-home
=> feat: product api routes for methods, product permissions (authentication middleware)

script/seed-users.js
=> fix: added passwords back into user seed file

client/components/cart.js, client/components/checkout.js, client/components/guestCart.js, client/components/navbar.js, client/components/order-confirmation.js, client/routes.js, public/style.css
=> Checkout style

client/components/checkout.js, client/components/order-confirmation.js, client/routes.js, public/style.css
=> order confirmation page

client/components/all-products.js, client/components/auth-form.js, client/components/cart.js, client/components/checkout.js, client/components/guestCart.js, client/store/products.js, script/seed.js, server/api/cart.js, server/api/products.js, server/auth/google.js, server/db/models/index.js
removed unused code and unnecessary comments
=> codebase cleanup

client/components/admin-editProduct.js, client/components/admin-viewProducts.js, client/components/admin-viewUsers.js, client/store/admin-products.js, server/api/products.js
- edit button renders an editProduct form
- upon submit of editForm, product updates
=> feat: editProduct form in admin view works

client/components/cart.js, client/components/checkout.js, client/components/guestCart.js, client/components/navbar.js, client/components/order-confirmation.js, client/components/single-product.js, client/store/user.js, server/api/cart.js
---
Removed commented-out code and superfluous console logs in most files. I didn't touch some of the admin or guest cart stuff because ... I was nervous! :)
=> Cleanup branch

client/components/admin-editProduct.js, client/components/admin-viewUsers.js, client/components/all-products.js, client/components/auth-form.js, client/components/checkout.js, client/store/admin-users.js, client/store/user.js, script/seed-products.js, server/api/products.js, server/db/models/user.js
- cleaned up some console.logs
- labeled some parts of code to make it more understandable
- also re-ordered some of the ducks so we can get the funnier ones up top (remember to npm run seed)
=> Chore: cleaning 

client/components/single-product.js, package-lock.json, package.json
feat: Added toast notification for Add to cart.
=> feat: Added toast notification for Add to cart

script/seed.js
- commented out old red/green console.log code, which used chalk (since Mikayla disabled it to try and prevent errors)
- added regular console.log that don't use chalk
=> fix: console.log red/green

client/components/checkout.js, server/auth/google.js
=> Pushing a working branch! ??
